spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/tagly
spring.datasource.username=postgres
spring.datasource.password=golumaskara
spring.jpa.hibernate.ddl-auto=update

#should always be 32 chars in length and something randomish
jwt.secret=yourVeryStrongSecretKey123456789

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB