spring.application.name=app

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tagly}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:golumaskara}
jwt.secret=${JWT_SECRET:yourVeryStrongSecretKey123456789}

minio.endpoint=${MINIO_ENDPOINT:http://127.0.0.1:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:tagly-posts}

spring.jpa.hibernate.ddl-auto=update

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.port=${PORT:8080}